example : example.c
	#
	# Compiling example
	#
	gcc -O3 -Wall -I../ example.c -o example

run : example
	#
	# Running example - compute average of a billion random numbers
	#
	./example

clean :
	rm -f *.exe
